# Generated by Django 6.0.1 on 2026-01-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0002_pagerevision_useractivity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useractivity",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at"],
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
            },
        ),
    ]
